runtime: php82
env: standard

handlers:
# 1. Layani semua file desain & aset secara otomatis tanpa diblokir
- url: /(.*\.(css|js|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot|ico|map))$
  static_files: \1
  upload: .*\.(css|js|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot|ico|map)$

# 2. Semua rute lainnya diarahkan ke skrip PHP router
- url: /.*
  script: auto